apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment2-config
data:
  test: |
    #!/bin/sh
    apk update
    apk add git
    apk update && apk add make
    apk add hugo
    git clone https://github.com/chazapis/hy548.git 
    cd /hy548
    git submodule init && git submodule update
    make

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assignment2-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  name: assignment2-service
  labels:
    run: assignment2-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: assignment2-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2-deployment
spec:
  selector:
    matchLabels:
      run: assignment2-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: assignment2-deployment
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: assignment2-pv-claim
        - name: config-volume
          configMap:
            name: assignment2-config
      containers:
        - name: nginx
          image: nginx:1.21.6-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: task-pv-storage
              mountPath: /usr/share/nginx/html
            - name: config-volume
              mountPath: /usr/share/nginx/
          command:
            - /bin/sh
            - /usr/share/nginx/html/test