apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment2-config
data:
  test: |
    #!/bin/sh
    apk update
    apk add git
    apk update && apk add make
    apk add hugo
    git clone https://github.com/chazapis/hy548.git 
    cd /hy548
    git submodule init && git submodule update
    make

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assignment2-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: assignment2-cronjob
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: task-pv-storage
              persistentVolumeClaim:
                claimName: assignment2-pv-claim
            - name: config-volume
              configMap:
                name: assignment2-config
          restartPolicy: OnFailure
          containers:
            - name: nginx
              image: nginx:1.21.6-alpine
              ports:
                - containerPort: 80
                  name: http
                  protocol: TCP
              volumeMounts:
                - name: task-pv-storage
                  mountPath: /usr/share/nginx/html
                - name: config-volume
                  mountPath: /usr/share/nginx/
              command:
                - /bin/sh
                - /usr/share/nginx/html/test
