apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment2-config
data:
  test: |
    #!/bin/sh
    apt update && apt upgrade
    apt install sudo
    apt install -y git
    apt install -y make
    apt install -y curl
    apt install -y tar 
    curl -L -o hugo_extended_0.96.0_Linux-64bit.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz
    tar -xf hugo_extended_0.96.0_Linux-64bit.tar.gz
    ./hugo
    git submodule init
    git submodule update
    make


---
apiVersion: batch/v1
kind: Job
metadata:
  name: assignment2-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/bin
          command:
            - /bin/sh
            - /usr/local/bin/test
      volumes:
        - name: config-volume
          configMap:
            name: assignment2-config
